version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=proyectodaw
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
  replica1:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  replica2:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - db
  replica3:
    build: .
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/code
    ports:
      - "8002:8002"
    depends_on:
      - db
  api:
    build: ../API
    command: python manage.py runserver 0.0.0.0:8005
    volumes:
      - .:/code
    ports:
      - "8005:8005"
    depends_on:
      - db